#include:amsmath
#include:array
#include:booktabs
#include:tabularx
#include:longtable
#include:multirow
#include:diagbox
#include:graphicx
#include:hyperref
#include:xparse
#include:ntheorem
#include:metalogo
#include:xcolor
#include:mhchem
#include:siunitx
#include:upgreek
#include:subcaption
\pkg#n